// export const SHOW_DOT_LOADER = "SHOW_DOT_LOADER";

// AUTHENTICATION ACTIONS
export const LOGIN_USER = 'LOGIN_USER';
export const USER_PERMISSIONS = 'USER_PERMISSIONS';

// LOADING
export const LOADING_TRUE = 'LOADING_TRUE';

// LOG FRAME ACTIONS
export const FILTER_INDICATOR_GRAPH_DATA =
  'FILTER_INDICATOR_GRAPH_DATA';
export const FILTER_INDICATOR_GRAPH_DATA_WITH_DATE =
  'FILTER_INDICATOR_GRAPH_DATA_WITH_DATE';
export const GET_INDICATORS_GRAPHDATA = 'GET_ALLINDICATORS_GRAPHDATA';
export const GET_INDICATORS_CATEGORY = 'GET_INDICATORS_CATEGORY';
export const GET_INDICATORS_GRAPHDATA_INDIVIDUAL =
  'GET_INDICATORS_GRAPHDATA_INDIVIDUAL';

// AUTOMATION ACTIONS
export const GET_AUTOMATION_DATA_BY_PARTNER =
  'GET_AUTOMATION_DATA_BY_PARTNER';
export const GET_AUTOMATION_DATA_BY_PROVINCE =
  'GET_AUTOMATION_DATA_BY_PROVINCE';
export const GET_AUTOMATION_DATA_BY_DISTRICT =
  'GET_AUTOMATION_DATA_BY_DISTRICT';
export const GET_AUTOMATION_DATA_BY_MUNICIPALITY =
  'GET_AUTOMATION_DATA_BY_MUNICIPALITY';

export const SELECT_AUTOMATION_DATA_BY_PROVINCE =
  'SELECT_AUTOMATION_DATA_BY_PROVINCE';
export const SELECT_AUTOMATION_DATA_BY_DISTRICT =
  'SELECT_AUTOMATION_DATA_BY_DISTRICT';
export const SELECT_AUTOMATION_DATA_BY_MUNICIPALITY =
  'SELECT_AUTOMATION_DATA_BY_MUNICIPALITY';

export const GET_AUTOMATION_BRANCHES_TABLE_DATA =
  'GET_AUTOMATION_BRANCHES_TABLE_DATA';
export const GET_AUTOMATION_BRANCHES_TABLE_DATA_BY_FEDERAL =
  'GET_AUTOMATION_BRANCHES_TABLE_DATA_BY_FEDERAL';
export const GET_AUTOMATION_BRANCHES_TABLE_DATA_BY_PARTNER =
  'GET_AUTOMATION_BRANCHES_TABLE_DATA_BY_PARTNER';

export const GET_SEARCHED_PARTNERS = 'GET_SEARCHED_PARTNERS';

export const GET_ALLPROVINCENAME_DATA = 'GET_ALLPROVINCENAME_DATA';
export const GET_ALLDISTRICTNAME_DATA = 'GET_ALLDISTRICTNAME_DATA';
export const GET_ALLMUNICIPALITYNAME_DATA =
  'GET_ALLMUNICIPALITYNAME_DATA';

export const FILTER_PARTNERS_SELECT = 'FILTER_PARTNERS_SELECT';
export const FILTER_PARTNERS_BY_FEDERAL =
  'FILTER_PARTNERS_BY_FEDERAL';
export const FILTER_PARTNERS_BY_FEDERAL_WITH_CLICKEDPARTNERS =
  'FILTER_PARTNERS_BY_FEDERAL_WITH_CLICKEDPARTNERS';

export const GET_DISTRICTDATA_BY_PROVINCE =
  'GET_DISTRICTDATA_BY_PROVINCE';
export const GET_MUNICIPALITYDATA_BY_DISTRICT =
  'GET_MUNICIPALITYDATA_BY_DISTRICT';

export const FILTER_AUTOMATION_DATA_FOR_VECTORTILES =
  'FILTER_AUTOMATION_DATA_FOR_VECTORTILES';
export const FILTER_DISTRICT_FROM_PROVINCE_COLOR =
  'FILTER_DISTRICT_FROM_PROVINCE_COLOR';

export const GET_TABLE_DATA_BY_PARTNERS_SELECT =
  'GET_TABLE_DATA_BY_PARTNERS_SELECT';

export const PARTNER_SELECT_WITH_OUTREACH_GET_PARTNER_CHOROPLETHDATA =
  'PARTNER_SELECT_WITH_OUTREACH_GET_PARTNER_CHOROPLETHDATA';

export const GET_TIMELINE_DATA = 'GET_TIMELINE_DATA';
export const TIMELINE_FILTER = 'TIMELINE_FILTER';
export const FILTER_AUTOMATION_BY_PROVINCE =
  'FILTER_AUTOMATION_BY_PROVINCE';

// Financial Data
export const GET_FINANCIAL_DATA = 'GET_FINANCIAL_DATA';
export const GET_FINANCIAL_PROGRAM = 'GET_FINANCIAL_PROGRAM';
export const GET_PARTNERS_LIST = 'GET_PARTNERS_LIST';
export const FILTER_FINANCIAL_DATA_FOR_GRAPH =
  'FILTER_FINANCIAL_DATA_FOR_GRAPH';
export const FILTER_PARTNERS_BY_TYPE = 'FILTER_PARTNERS_BY_TYPE';
