// export const SHOW_DOT_LOADER = "SHOW_DOT_LOADER";

// AUTHENTICATION ACTIONS
export const LOGIN_USER = 'LOGIN_USER';
export const USER_PERMISSIONS = 'USER_PERMISSIONS';

// LOADING
export const LOADING_TRUE = 'LOADING_TRUE';

// LOG FRAME ACTIONS
export const FILTER_INDICATOR_GRAPH_DATA =
  'FILTER_INDICATOR_GRAPH_DATA';
export const FILTER_INDICATOR_GRAPH_DATA_WITH_DATE =
  'FILTER_INDICATOR_GRAPH_DATA_WITH_DATE';
export const FILTER_OUTPUT_INDICATOR_WITH_PERCENT_OR_NUMBER =
  'FILTER_OUTPUT_INDICATOR_WITH_PERCENT_OR_NUMBER';
export const GET_INDICATORS_GRAPHDATA = 'GET_ALLINDICATORS_GRAPHDATA';
export const GET_INDICATORS_CATEGORY = 'GET_INDICATORS_CATEGORY';
export const GET_INDICATORS_GRAPHDATA_INDIVIDUAL =
  'GET_INDICATORS_GRAPHDATA_INDIVIDUAL';
export const GET_PLANNED_ACHIEVED_DATA_FOR_1STPIECHARTS =
  'GET_PLANNED_ACHIEVED_DATA_FOR_1STPIECHARTS';
export const GET_PLANNED_ACHIEVED_DATA_FOR_2NDPIECHARTS =
  'GET_PLANNED_ACHIEVED_DATA_FOR_2NDPIECHARTS';

// AUTOMATION ACTIONS
export const GET_AUTOMATION_DATA_BY_PARTNER =
  'GET_AUTOMATION_DATA_BY_PARTNER';
export const GET_AUTOMATION_DATA_BY_PROVINCE =
  'GET_AUTOMATION_DATA_BY_PROVINCE';
export const GET_AUTOMATION_DATA_BY_DISTRICT =
  'GET_AUTOMATION_DATA_BY_DISTRICT';
export const GET_AUTOMATION_DATA_BY_MUNICIPALITY =
  'GET_AUTOMATION_DATA_BY_MUNICIPALITY';

export const SELECT_AUTOMATION_DATA_BY_PROVINCE =
  'SELECT_AUTOMATION_DATA_BY_PROVINCE';
export const SELECT_AUTOMATION_DATA_BY_DISTRICT =
  'SELECT_AUTOMATION_DATA_BY_DISTRICT';
export const SELECT_AUTOMATION_DATA_BY_MUNICIPALITY =
  'SELECT_AUTOMATION_DATA_BY_MUNICIPALITY';

export const GET_AUTOMATION_BRANCHES_TABLE_DATA =
  'GET_AUTOMATION_BRANCHES_TABLE_DATA';
export const GET_AUTOMATION_BRANCHES_TABLE_DATA_BY_FEDERAL =
  'GET_AUTOMATION_BRANCHES_TABLE_DATA_BY_FEDERAL';
export const GET_AUTOMATION_BRANCHES_TABLE_DATA_BY_PARTNER =
  'GET_AUTOMATION_BRANCHES_TABLE_DATA_BY_PARTNER';

export const GET_SEARCHED_PARTNERS = 'GET_SEARCHED_PARTNERS';

export const GET_ALLPROVINCENAME_DATA = 'GET_ALLPROVINCENAME_DATA';
export const GET_ALLDISTRICTNAME_DATA = 'GET_ALLDISTRICTNAME_DATA';
export const GET_ALLMUNICIPALITYNAME_DATA =
  'GET_ALLMUNICIPALITYNAME_DATA';

export const FILTER_PARTNERS_SELECT = 'FILTER_PARTNERS_SELECT';
export const FILTER_PARTNERS_BY_FEDERAL =
  'FILTER_PARTNERS_BY_FEDERAL';
export const FILTER_PARTNERS_BY_FEDERAL_CLICKED_EXCEPTION =
  'FILTER_PARTNERS_BY_FEDERAL_CLICKED_EXCEPTION';
export const FILTER_PARTNERS_BY_FEDERAL_WITH_CLICKEDPARTNERS =
  'FILTER_PARTNERS_BY_FEDERAL_WITH_CLICKEDPARTNERS';

export const GET_DISTRICTDATA_BY_PROVINCE =
  'GET_DISTRICTDATA_BY_PROVINCE';
export const GET_MUNICIPALITYDATA_BY_DISTRICT =
  'GET_MUNICIPALITYDATA_BY_DISTRICT';

export const FILTER_AUTOMATION_DATA_FOR_VECTORTILES =
  'FILTER_AUTOMATION_DATA_FOR_VECTORTILES';
export const FILTER_DISTRICT_FROM_PROVINCE_COLOR =
  'FILTER_DISTRICT_FROM_PROVINCE_COLOR';

export const GET_TABLE_DATA_BY_PARTNERS_SELECT =
  'GET_TABLE_DATA_BY_PARTNERS_SELECT';

export const PARTNER_SELECT_WITH_OUTREACH_GET_PARTNER_CHOROPLETHDATA =
  'PARTNER_SELECT_WITH_OUTREACH_GET_PARTNER_CHOROPLETHDATA';

export const GET_TIMELINE_DATA = 'GET_TIMELINE_DATA';
export const TIMELINE_FILTER = 'TIMELINE_FILTER';
export const FILTER_AUTOMATION_BY_PROVINCE =
  'FILTER_AUTOMATION_BY_PROVINCE';
export const GET_AUTOMATION_DATA_FOR_TIMELINE =
  'GET_AUTOMATION_DATA_FOR_TIMELINE';
export const AUTOMATION_MUNICIPALITY_LEGEND =
  'AUTOMATION_MUNICIPALITY_LEGEND';
export const AUTOMATION_PROVINCE_LEGEND =
  'AUTOMATION_PROVINCE_LEGEND';
export const AUTOMATION_DISTRICT_LEGEND =
  'AUTOMATION_DISTRICT_LEGEND';

// FINANCIAL DATA ACTIONS
export const GET_PARTNERS_DATA_ALL = 'GET_PARTNERS_DATA_ALL';
export const GET_FINANCIAL_DATA_REQUEST =
  'GET_FINANCIAL_DATA_REQUEST';
export const GET_FINANCIAL_DATA_SUCCESS =
  'GET_FINANCIAL_DATA_SUCCESS';
export const GET_FINANCIAL_PROGRAM = 'GET_FINANCIAL_PROGRAM';
export const GET_PARTNERS_LIST = 'GET_PARTNERS_LIST';
export const FILTER_FINANCIAL_DATA_FOR_GRAPH =
  'FILTER_FINANCIAL_DATA_FOR_GRAPH';
export const FILTER_PARTNERS_BY_TYPE = 'FILTER_PARTNERS_BY_TYPE';
export const FILTER_TABLE_BY_PARTNER = 'FILTER_TABLE_BY_PARTNER';
export const GET_SEARCHED_DATA_ON_TABLE =
  'GET_SEARCHED_DATA_ON_TABLE';

export const FILTER_BAR_DATA_AFTER_CLICK =
  'FILTER_BAR_DATA_AFTER_CLICK';

// PARTNERSHIP DATA ACTIONS
export const GET_PROJECT_LIST_DATA = 'GET_PROJECT_LIST_DATA';
export const GET_PARTNERSHIP_PARTNERS_LIST =
  'GET_PARTNERSHIP_PARTNERS_LIST';
export const FILTER_PARTNERSHIP_PARTNERS_LIST_BY_PARTNER_TYPE =
  'FILTER_PARTNERSHIP_PARTNERS_LIST_BY_PARTNER_TYPE';
export const FILTER_FINANCIALDATA_OF_DISTRICT_FROM_PROVINCE =
  'FILTER_FINANCIALDATA_OF_DISTRICT_FROM_PROVINCE';
export const FILTER_FINANCIALDATA_OF_MUNICIPALITY_FROM_DISTRICT =
  'FILTER_FINANCIALDATA_OF_MUNICIPALITY_FROM_DISTRICT';
export const FILTER_FINANCIALDATA_WITH_ALL_FILTERS =
  'FILTER_FINANCIALDATA_WITH_ALL_FILTERS';
export const FILTER_BARDATA_BY_BENEF_BUDGET_WITH_PROVINCE_ONLY =
  'FILTER_BARDATA_BY_BENEF_BUDGET_WITH_PROVINCE_ONLY';
export const GET_PARTNERSHIP_INVESTMENT_FOCUS =
  'GET_PARTNERSHIP_INVESTMENT_FOCUS';
export const GET_BARDATA_BY_BENEF_BUDGET =
  'GET_BARDATA_BY_BENEF_BUDGET';
export const GET_BARDATA_BY_INVESTMENTFOCUS =
  'GET_BARDATA_BY_INVESTMENTFOCUS';
export const FILTER_BARDATA_BY_INVESTMENTFOCUS =
  'FILTER_BARDATA_BY_INVESTMENTFOCUS';
export const GET_LEVERAGE_DATA = 'GET_LEVERAGE_DATA';
export const FILTER_LEVERAGE_DATA = 'FILTER_LEVERAGE_DATA';
export const GET_MAP_DATA_BY_PROVINCE = 'GET_MAP_DATA_BY_PROVINCE';
export const GET_MAP_DATA_BY_DISTRICT = 'GET_MAP_DATA_BY_DISTRICT';
export const GET_MAP_DATA_BY_MUNICIPALITY =
  'GET_MAP_DATA_BY_MUNICIPALITY';
export const GET_FILTERED_MAP_DATA = 'GET_FILTERED_MAP_DATA';
export const GET_RADIAL_DATA_REQUEST = 'GET_RADIAL_DATA_REQUEST';
export const GET_RADIAL_DATA_SUCCESS = 'GET_RADIAL_DATA_SUCCESS';
export const GET_RADIAL_DATA_FAILED = 'GET_RADIAL_DATA_FAILED';
export const FILTER_RADIAL_DATA = 'FILTER_RADIAL_DATA';
export const GET_SPIDERCHART_DATA = 'GET_SPIDERCHART_DATA';
export const GET_SANKEY_CHART_DATA = 'GET_SANKEY_CHART_DATA';
export const FILTER_SANKEY_CHART_DATA = 'FILTER_SANKEY_CHART_DATA';
export const GET_OVERVIEW_DATA = 'GET_OVERVIEW_DATA';
export const FILTER_OVERVIEW_DATA = 'FILTER_OVERVIEW_DATA';
export const GET_MAP_DATA = 'GET_MAP_DATA';
export const FILTER_DISTRICTLIST_FROM_PROVINCE =
  'FILTER_DISTRICTLIST_FROM_PROVINCE';
export const FILTER_MUNLIST_FROM_DISTRICT =
  'FILTER_MUNLIST_FROM_DISTRICT';
export const FILTER_FINANCIALDATA_WITH_ALL_FILTERS_AND_FEDERAL =
  'FILTER_FINANCIALDATA_WITH_ALL_FILTERS_AND_FEDERAL';
export const FILTER_MAPDATA_OF_CIRCLE_MARKER_WITH_VIEW_DATABY =
  'FILTER_MAPDATA_OF_CIRCLE_MARKER_WITH_VIEW_DATABY';
export const FILTER_MAPDATA_OF_CHOROPLETH_WITH_FEDERAL =
  'FILTER_MAPDATA_OF_CHOROPLETH_WITH_FEDERAL';
export const GET_PARTNERSHIP_ALL_DATA = 'GET_PARTNERSHIP_ALL_DATA';
export const RESET_BAR_DATA = 'GET_RESET_BAR_DATA';
export const RESET_BAR_DATA_BY_INVESTMENT_FOCUS =
  'RESET_BAR_DATA_BY_INVESTMENT_FOCUS';
export const RESET_RADIAL_DATA = 'RESET_RADIAL_DATA';
export const RESET_SANKEYCHART_DATA = 'RESET_SANKEYCHART_DATA';
export const RESET_OVERVIEW_DATA = 'RESET_OVERVIEW_DATA';
export const RESET_LEVERAGE_DATA = 'RESET_LEVERAGE_DATA';
export const FILTER_TIMELINE_DATA = 'FILTER_TIMELINE_DATA';
export const FILTER_LEVERAGE_DATA_FOR_BARCLICK =
  'FILTER_LEVERAGE_DATA_FOR_BARCLICK';
export const FILTER_BENEFBUDGET_DATA_FOR_BARCLICK =
  'FILTER_BENEFBUDGET_DATA_FOR_BARCLICK';
export const FILTER_MAPDATA_CHOROPLETH = 'FILTER_MAPDATA_CHOROPLETH';
export const GET_PARTNERSHIP_PARTNERSTYPE_LIST =
  'GET_PARTNERSHIP_PARTNERSTYPE_LIST';
export const GET_PARTNERSHIP_TIMELINE_DATA_API =
  'GET_PARTNERSHIP_TIMELINE_DATA_API';

// PRODUCT PROCESS ACTIONS
export const GET_PRODUCT_PROCESS_DATA = 'GET_PRODUCT_PROCESS_DATA';
export const GET_PRODUCT_PROCESS_LIST_REQUEST =
  'GET_PRODUCT_PROCESS_LIST_REQUEST';
export const GET_PRODUCT_PROCESS_LIST_SUCCESS =
  'GET_PRODUCT_PROCESS_LIST_SUCCESS';
export const GET_PRODUCT_PROCESS_LIST_FAILURE =
  'GET_PRODUCT_PROCESS_LIST_FAILURE';
export const GET_INITIAL_CHART_DATA = 'GET_INITIAL_CHART_DATA';
export const FILTER_PRODUCT_NAME_LIST = 'FILTER_PRODUCT_NAME_LIST';
export const FILTER_PARTNER_NAME_LIST = 'FILTER_PARTNER_NAME_LIST';
export const FILTER_ALL_CHART_PP = 'FILTER_ALL_CHART_PP';
export const RESET_ALL_CHART_PP = 'RESET_ALL_CHART_PP';
export const FILTER_BAR_POPUP = 'FILTER_BAR_POPUP';

// PAYMENT SYSTEMS ACTIONS
export const GET_PAYMENT_SYSTEMS_DATA = 'GET_PAYMENT_SYSTEMS_DATA';

// Outreach Actions
export const GET_OUTREACH_SECONDARY_DATA =
  'GET_OUTREACH_SECONDARY_DATA';
export const GET_OUTREACH_BY_PROVINCE = 'GET_OUTREACH_BY_PROVINCE';
export const GET_OUTREACH_BY_DISTRICT = 'GET_OUTREACH_BY_DISTRICT';
export const GET_OUTREACH_BY_MUNICIPALITY =
  'GET_OUTREACH_BY_MUNICIPALITY';
export const GET_OUTREACH_BY_PRIMARY_DATA =
  'GET_OUTREACH_BY_PRIMARY_DATA';

// MFS ACTIONS
export const GET_MFS_LIST_REQUEST = 'GET_MFS_LIST_REQUEST';
export const GET_MFS_LIST_SUCCESS = 'GET_MFS_LIST_SUCCESS';
export const GET_MFS_LIST_FAILURE = 'GET_MFS_LIST_FAILURE';

export const GET_MFS_INNOVATIONLIST = 'GET_MFS_INNOVATIONLIST';
export const GET_MFS_ACHIEVEMENTLIST = 'GET_MFS_ACHIEVEMENTLIST';
export const GET_MFS_PARTNERLIST = 'GET_MFS_PARTNERLIST';

export const GET_MFS_OVERVIEW_DATA = 'GET_MFS_OVERVIEW_DATA';
export const FILTER_MFS_OVERVIEW_DATA = 'FILTER_MFS_OVERVIEW_DATA';

export const FILTER_MFS_LIST_BY_PARTNERINSTITUTION =
  'FILTER_MFS_LIST_BY_PARTNERINSTITUTION';
export const FILTER_MFS_LIST_BY_KEY_INNOVATION =
  'FILTER_MFS_LIST_BY_KEY_INNOVATION';
export const FILTER_MFS_CHOROPLETH_DATA =
  'FILTER_MFS_CHOROPLETH_DATA';
export const FILTER_MFS_CHART_DATA_BY_ACHIEVEMENT =
  'FILTER_MFS_CHART_DATA_BY_ACHIEVEMENT';
export const FILTER_MFS_CHART_DATA_BY_PARTNER =
  'FILTER_MFS_CHART_DATA_BY_PARTNER';
export const FILTER_MFS_CHART_DATA_BY_PARTNER_WITH_INNOVATION =
  'FILTER_MFS_CHART_DATA_BY_PARTNER_WITH_INNOVATION';
export const FILTER_MFS_MAP_PIE_DATA = 'FILTER_MFS_MAP_PIE_DATA';
export const FILTER_MFS_CHART_DATA_BY_DISTRICT_ID =
  'FILTER_MFS_CHART_DATA_BY_DISTRICT_ID';

// INSURANCE ACTIONs
export const GET_INSURANCE_DATA_REQUEST =
  'GET_INSURANCE_DATA_REQUEST';
export const GET_INSURANCE_DATA_SUCCESS =
  'GET_INSURANCE_DATA_SUCCESS';
