// export const SHOW_DOT_LOADER = "SHOW_DOT_LOADER";

// LOG FRAME ACTIONS
export const GET_INDICATORS_GRAPHDATA = 'GET_ALLINDICATORS_GRAPHDATA';
export const GET_INDICATORS_CATEGORY = 'GET_INDICATORS_CATEGORY';
// export const STOP_SUBMISSION_LOADER = 'STOP_SUBMISSION_LOADER';
// export const GET_SUBMISSION_DETAIL = 'GET_SUBMISSION_DETAIL';
// export const POST_SUBMISSION_DETAIL = 'POST_SUBMISSION_DETAIL';
// export const UPDATE_SUBMISSION_DETAIL = 'UPDATE_SUBMISSION_DETAIL';
// export const TOGGLE_NULL_SUBMISSIONS_ANSWER =
//   'TOGGLE_NULL_SUBMISSIONS_ANSWER';
// export const SHOW_SUBMISSION_ERR_MSG = 'SHOW_SUBMISSION_ERR_MSG';
