# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm install
    - run: npm run prebuild
    
    - run:   echo ::set-env name=PULL_NUMBER::$(echo "$GITHUB_REF" | awk -F / '{print $3}')
      shell: bash
    - uses: yg/deploy-surge@v1.0.0
      with:
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        BUILD_DIRECTORY: ${{ secrets.BUILD_DIRECTORY }}
        DOMAIN_NAME: pr-${{env.PULL_NUMBER}}-sakchyam-naxa.surge.sh
